### ISSUE TITLE
vinyl file pipe

### ISSUE THREAD

**Issue by pruttned** [twolfson/pixelsmith#10]
Hi,
pipe method was removed from the vinyl file in v2.0.0
(https://github.com/gulpjs/vinyl/issues/107  , 
https://github.com/gulpjs/vinyl/commit/d14ba4a7b51f0f3682f65f2aa4314d981eb1029d )
therefore pixelsmith fails at this line 
https://github.com/twolfson/pixelsmith/blob/master/lib/engine.js#L40

**Comment by twolfson** [comment]
I posted a question about alternatives on the linked issue as we will have to add support but also add more tests. I'll check back on this in 1 week as it seems `gulp@3` is still on `vinyl-fs@0.x.x` which is on `vinyl@0.x.x`:

https://github.com/gulpjs/gulp/blob/v3.9.1/package.json#L41

https://github.com/gulpjs/vinyl-fs/blob/v0.3.14/package.json#L21

Reminder: https://twitter.com/twolfsn/status/795367333682290688

**Comment by zolotykh** [comment]
@twolfson is there a solution?

**Comment by twolfson** [comment]
The Gulp team never replied on the original issue (https://github.com/gulpjs/vinyl/issues/107) so we're still lacking support. Gulp still seems to be on the `vinyl-fs@0.x.x` version though so this hasn't become a priority

When it does become a priority, I feel like we'll probably write a small library (e.g. `vinyl-pipe`) which copy/pastes the original behavior (https://github.com/gulpjs/vinyl/commit/d14ba4a7b51f0f3682f65f2aa4314d981eb1029d). Is there any reason y'all are looking for `vinyl@2` support?

**Comment by twolfson** [comment]
It looks like `gulp@4` was released over the past few days as I was notified in https://github.com/twolfson/gulp.spritesmith/issues/135

https://github.com/gulpjs/gulp/releases/tag/v4.0.0

This is now a priority but I'm pretty swamped. If someone doesn't beat me to it, then I'll resolve this by the end of the weekend

**Comment by twolfson** [comment]
Looking into handling this now

**Comment by twolfson** [comment]
This has been resolved in `2.2.0`. I'll be publishing upgrades for `spritesmith`, `gulp.spritesmith`, and `grunt-spritesmith` shortly after that. Additionally, this impacts all `spritesmith` engines so I'll be adding support to `canvassmith`, `gmsmith`, and `phantomjssmith` after that
