### ISSUE TITLE
Update Dependency to ndarray-fill

### ISSUE THREAD

**Issue by ghost** [twolfson/pixelsmith#14]
NPM have raised an issue with one of your dependencies, I have fixed it here;
https://github.com/DarrenMack-OD/pixelsmith

**Comment by twolfson** [comment]
What's the reason for the `ndarray-fill` upgrade? Is something deprecated?

**Comment by ghost** [comment]
Yeah it would seem it has a minor security issue that NPM is moaning about...

**Comment by twolfson** [comment]
Ah, word. Would you mind submitting this as a PR?

**Comment by twolfson** [comment]
After seeing the PR, it seems that this upgrade is for a patch update -- we don't need to do anything for this. `npm` will use the latest patch version automatically
