### ISSUE TITLE
Include filename when throwing file related errors

### ISSUE THREAD

**Issue by mohitk05** [twolfson/pixelsmith#18]
Currently if a file has invalid signature (my usecase, might be any other file error), the error thrown looks like this: `Error: Invalid file signature.`. Including filename will help identify the exact file that is causing this. 
Probable solution: In `engine.js` at current line number 71, `callback`, we can have a custom function as a callback:
```js
(err, ...args) => {
	if(err) err.concat(file); //Add file name
	callback(err, ...args);
}
```

**Comment by twolfson** [comment]
Can you double check your `pixelsmith` version? We added this functionality in `2.4.1`:

https://github.com/twolfson/pixelsmith/commit/ca72a396f6118c557c4c9b96f5f46f4a68a0d499
