### ISSUE TITLE
EMFILE: too many open files

### ISSUE THREAD

**Issue by sindreslungaard** [twolfson/pixelsmith#20]
Running `createImages` with a large number of files will result in an error "EMFILE: too many open files".

I was able to work around this by changing the `createImages` function from
```js
createImages: function (files, callback) {
    // In parallel, calculate each of our images
    async.map(files, this.createImage.bind(this), callback);
}
```
to
```js
createImages: function (files, callback) {
    // In parallel, calculate each of our images
    async.mapLimit(files, 10, this.createImage.bind(this), callback);
}
```

**Comment by twolfson** [comment]
How many files were you dealing with?

**Comment by sindreslungaard** [comment]
> How many files were you dealing with?

Just over 11000 small images

**Comment by twolfson** [comment]
What's your use case? That seems rather excessive and not something we should support for websites =/ (e.g. resulting spritesheet is still quite large, thus defeating purpose)

**Comment by sindreslungaard** [comment]
I'm working on a game that needs to draw many many sprites and every drawcall to the gpu counts, so it's essential that all the sprites are packed into a single texture. However the individual sprites are very small and being scaled up in the game, so even with 11000 images the actual spritesheet is no larger than 4096x4096.

We use spritesmith to write tools that automate the process of bundling these sprites and relevant data into spritesheets and configurations

**Comment by twolfson** [comment]
Always fascinating to hear how `spritesmith` transcends it initial use case =) I think the solution to this is:

- Use `mapLimit` with an infinite upper bound (or `map` if parameter isn't present)
- Allow configuration to include some limit functionality
    - We could also do some `try/except` backoff looping but this is simpler

Fwiw, `EMFILE` can sometimes be worked around via `ulimit` https://stackoverflow.com/a/21201405/1960509 (though you're  even exceeding their number O_O

I'll add support for this by the end of the weekend

**Comment by sindreslungaard** [comment]
Sounds good 👍

> Fwiw, `EMFILE` can sometimes be worked around via `ulimit`

From what I could find there's no easy way to achieve this on Windows. Maybe with WSL, but i'm not sure it's a good idea to increase the system-wide limit that high :D

**Comment by twolfson** [comment]
We've added `options.concurrentFileLimit` to the `Engine` constructor in `2.5.0`:

https://github.com/twolfson/pixelsmith/tree/2.5.0#engineoptions

This will automatically propagate to `spritesmith` and other higher level interfaces (e.g. `grunt-spritesmith`, `gulp.spritesmith`) due to floating semver dependencies.

To use this in `spritesmith` (which it sounds like you're using directly), it should be the `params.engineOpts` parameter in your constructor:

https://github.com/twolfson/spritesmith/tree/3.4.0#new-spritesmithparams
