### ISSUE TITLE
Update save-pixels dependency

### ISSUE THREAD

**Issue by TimVevida** [twolfson/pixelsmith#6]
save-pixels v2.2.0 uses the deprecated pngjs2, save-pixels v2.3.0 uses v2.0 of pngjs, which is the re-integration of pngjs2.

**Comment by twolfson** [comment]
Would you be interesting in opening a PR to repair this?

**Comment by TimVevida** [comment]
Hello Todd,

I was updating my NPM dependencies, and pixelsmith is one of the
dependencies of my dependencies, which generated a warning, because the
mentioned dependency of pixelsmith is out-of-date.
I have no knowledge of the exact workings of pixelsmith and therefore do
not feel comfortable making a PR.

Tim Havinga

Vevida
www.vevida.com
timhavinga@vevida.com
050 211 0100

Op 14-12-2015 om 18:57 schreef Todd Wolfson:

**Comment by twolfson** [comment]
Ah, k. Thanks for the heads up

**Comment by twolfson** [comment]
This has been patched/released in `2.0.1`.
