### ISSUE TITLE
Update get-pixels dependency

### ISSUE THREAD

**Issue by martinkadlec0** [twolfson/pixelsmith#8]
Hi, could you please update the get-pixels dependency from 3.2.3 to 3.3.0? The older version uses deprecated version of pngjs.

**Comment by twolfson** [comment]
Would you be interested in submitting a PR to resolve this?

**Comment by martinkadlec0** [comment]
Pull request for the get-pixels isn't a problem: https://github.com/twolfson/pixelsmith/pull/9

Although the rest of the dependencies would need some updates as well :D But as long as they don't throw deprecated warning at me...

**Comment by twolfson** [comment]
This has been resolved via #9 and released in `2.1.1`
